/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.persistence.*;
import javax.swing.*;

/**
 *
 * @author me
 */
public class SetupUI extends javax.swing.JPanel {
    public static final String PERSISTENCE_UNIT_NAME="PersistenceUnit";
    public static final EntityManagerFactory factory = Persistence.createEntityManagerFactory(PERSISTENCE_UNIT_NAME);
    private JFrame window;
    private JPanel cards;
    private StudentsListUI studentListUI;
    private GameTypeUI gameTypeUI;
    private LevelTypeUI levelTypeUI;
    private StartUI startUI;
    private GameUI gameUI;
    private StoryUI storyUI;
    private SongUI songUI;
    /**
     * Creates new form SetupUI
     */
    public SetupUI() {
        window = new JFrame();
        CardLayout cardLayout = new CardLayout();
        cards = new JPanel(cardLayout);
        studentListUI = new StudentsListUI();
        gameTypeUI = new GameTypeUI();
        levelTypeUI = new LevelTypeUI();
        startUI = new StartUI();
        cards.add(studentListUI,"StudentList");
        cards.add(gameTypeUI,"GameType"); 
        cards.add(levelTypeUI,"Level Type");
        cards.add(startUI,"Start");
        window.setContentPane(cards);
        cardLayout.next(cards);;
        window.setVisible(true);
        initComponents();
    }
    public static void main (String[] args) {
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupUI();
                //cards.next(this);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
