/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.*;
import javax.persistence.*;
import javax.swing.*;

/**
 *
 * @author me
 */
public class SetupUI extends javax.swing.JPanel {
    //TODO: USE JFRAME INSTEAD
    public static final String PERSISTENCE_UNIT_NAME="PersistenceUnit";
    public static final EntityManagerFactory factory = Persistence.createEntityManagerFactory(PERSISTENCE_UNIT_NAME);
    private JFrame window;
    private AboutUI aboutUI;
    private StudentsListUI studentListUI;
    private GameTypeUI gameTypeUI;
    private LevelUI speedTypeUI;
    private StartUI startUI;
    private GameUI gameUI;
    private StoryUI storyUI;
    private SongUI songUI;
    static private CardLayout cardLayout;
    static private JPanel cards;
    static int activityType=2;//Story is default activity
    static int activityLevel=0;//Default level is 0

    public static int getActivityType() {
        return activityType;
    }

    public static void setActivityType(int activityType) {
        SetupUI.activityType = activityType;
    }

    public static int getActivityLevel() {
        return activityLevel;
    }

    public static void setActivityLevel(int activityLevel) {
        SetupUI.activityLevel = activityLevel;
    }
    
    /**
     * Creates new form SetupUI
     */
    public SetupUI() {
        window = new JFrame();
        cardLayout = new CardLayout();
        cards = new JPanel(cardLayout);
        aboutUI = new AboutUI();
        studentListUI = new StudentsListUI();
        gameTypeUI = new GameTypeUI();
        speedTypeUI = new LevelUI();
        startUI = new StartUI();
        cards.add(aboutUI, "AboutSoftware");
        cards.add(studentListUI,"StudentList");
        cards.add(gameTypeUI,"GameType"); 
        cards.add(speedTypeUI,"Speed");
        cards.add(startUI,"Start");
        window.setContentPane(cards);
        initComponents();
        class TimerHandler implements ActionListener {

            @Override
            public void actionPerformed(ActionEvent ae) {
        //        window.setTitle("Fun Learn");
            }
            
        }
        TimerHandler timerHandler = new TimerHandler();
        Timer timer1 = new Timer(7000,timerHandler);
        
        window.setSize(1000,700);
        window.setTitle("Fun Learn");
        window.setVisible(true);
        timer1.start();
        window.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);        
        window.addWindowListener(new WindowAdapter(){
                @Override
                public void windowClosing(WindowEvent e){
                    int i=JOptionPane.showConfirmDialog(window, "Are you sure you want to close?", "Confirm close", JOptionPane.YES_NO_OPTION);
                    if(i == 0)
                        System.exit(0);
                }
            });
    }

    static public JPanel getCards() {
        return cards;
    }

    public void setCards(JPanel cards) {
        this.cards = cards;
    }

    static public CardLayout getCardLayout() {
        return cardLayout;
    }

    public void setCardLayout(CardLayout cardLayout) {
        this.cardLayout = cardLayout;
    }
    public static void main (String[] args) {
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupUI().setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
