package view;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sonam
 */
public class StartUI extends javax.swing.JPanel {
    /**
     * Creates new form StartUI
     */
    public StartUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPlaying = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        startPlaying.setBackground(new java.awt.Color(0, 204, 204));
        startPlaying.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        startPlaying.setForeground(new java.awt.Color(204, 0, 0));
        startPlaying.setText("Let's Start Playing!");
        startPlaying.setFocusPainted(false);
        startPlaying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPlayingActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(startPlaying, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(startPlaying, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startPlayingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPlayingActionPerformed
        switch (SetupUI.activityType) {
            case 1:
                GameUI gameUI = new GameUI(SetupUI.activityLevel,StudentsListUI.getPlayerController().getPlayerTablemodel().getPlayerIDs(),StudentsListUI.getPlayerController().getPlayerTablemodel().getPlayerList());
                ;
                gameUI.setVisible(true);
                gameUI.start();
                break;
            case 2:
                StoryUI storyUI = new StoryUI(SetupUI.activityLevel);
                storyUI.setVisible(true);
                storyUI.start();
                break;
            case 3:
                SongUI songUI = new SongUI(SetupUI.activityLevel);
                songUI.setVisible(true);
                songUI.start();
                break;
            default:
                SongUI songDef = new SongUI(SetupUI.activityLevel);
                songDef.setVisible(true);
                songDef.start();
        }
    }//GEN-LAST:event_startPlayingActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SetupUI.getCardLayout().previous(SetupUI.getCards());
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton startPlaying;
    // End of variables declaration//GEN-END:variables
}
