package view;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sonam
 */
public class StartUI extends javax.swing.JPanel {
    /**
     * Creates new form StartUI
     */
    public StartUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPlaying = new javax.swing.JButton();

        startPlaying.setText("Let's Start Playing!");
        startPlaying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPlayingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(startPlaying, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(startPlaying, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startPlayingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPlayingActionPerformed
        switch (SetupUI.activityType) {
            case 1:
                GameUI gameUI = new GameUI(SetupUI.activityLevel,StudentsListUI.getPlayerController().getPlayerTablemodel().getPlayerIDs(),StudentsListUI.getPlayerController().getPlayerTablemodel().getPlayerList());
                ;
                gameUI.setVisible(true);
                gameUI.start();
                break;
            case 2:
                StoryUI storyUI = new StoryUI(SetupUI.activityLevel);
                storyUI.setVisible(true);
                storyUI.start();
                break;
            case 3:
                SongUI songUI = new SongUI(SetupUI.activityLevel);
                songUI.setVisible(true);
                songUI.start();
                break;
            default:
                SongUI songDef = new SongUI(SetupUI.activityLevel);
                songDef.setVisible(true);
                songDef.start();
        }
    }//GEN-LAST:event_startPlayingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startPlaying;
    // End of variables declaration//GEN-END:variables
}
